ci(gh/wf/autofix): add formatting to autofix
Signed-off-by: Ian Lewis <ian@ianlewis.org>

diff --git a/.github/workflows/pull_request.autofix.yml b/.github/workflows/pull_request.autofix.yml
--- a/.github/workflows/pull_request.autofix.yml
+++ b/.github/workflows/pull_request.autofix.yml
@@ -53,5 +53,28 @@ jobs:
         run: make update-lockfiles
 
       - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
+        id: lockfiles
         with:
-          commit-message: "ci(deps): update lockfiles"
+          fail-fast: false
+          commit-message: "chore(deps): update lockfiles"
+
+      - name: format files
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: make format
+
+      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
+        id: formatting
+        with:
+          fail-fast: false
+          commit-message: "fix(all): formatting"
+
+      - name: check autofix
+        env:
+          LOCKFILES_AUTOFIXED: "${{ steps.lockfiles.outputs.autofix_started }}"
+          FORMATTING_AUTOFIXED: "${{ steps.formatting.outputs.autofix_started }}"
+        run: |
+          set -euo pipefail
+          # If either autofix was started then fail here.
+          [[ "${LOCKFILES_AUTOFIXED}" != "true" ]]
+          [[ "${FORMATTING_AUTOFIXED}" != "true" ]]
